#!/bin/bash

set -eo pipefail

DIR=`dirname $0`
PROJ_ROOT="$DIR/.."

"$PROJ_ROOT/node_modules/.bin/prettier" "$PROJ_ROOT/**/**/*.sol" -c
"$PROJ_ROOT/node_modules/.bin/prettier" "$PROJ_ROOT/**/**/*.js" -c
"$PROJ_ROOT/node_modules/.bin/prettier" "$PROJ_ROOT/**/**/*.ts" -c